# Generated by Django 4.2 on 2023-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
